# Generated by Django 5.0.6 on 2024-06-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_author_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
        migrations.AddField(
            model_name="post",
            name="name",
            field=models.CharField(default="User", max_length=30),
        ),
        migrations.DeleteModel(
            name="Author",
        ),
    ]
